jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 17
    - continue-on-error: true
      uses: gradle/gradle-build-action@v2
      with:
        arguments: app:assembleDebug
  publish:
    name: Publish to MavenLocal
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 17
    - continue-on-error: true
      uses: gradle/gradle-build-action@v2
      with:
        arguments: publishToMavenLocal
name: CI
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
