jobs:
  release:
    name: Github Release
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 17
    - continue-on-error: true
      name: Build APK
      uses: gradle/gradle-build-action@v2
      with:
        arguments: app:assembleRelease
    - continue-on-error: true
      name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: app/build/outputs/apk/release/app-release.apk
        token: ${{ secrets.GITHUB_TOKEN }}
name: Release
on:
  repository_dispatch:
    types: trigger-ga___release.yml
